name: Bioinfo-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Conda Environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: human_intestinal.yml
          cache-environment: true
          # We disable the custom shell generation to stop the cleanup error
          generate-run-shell: false

      - name: Install and Run
        # We use standard bash, but we add 'micromamba run -n <env_name>' 
        # to ensure it uses your conda-forge environment
        run: |
          micromamba run -n human_intestinal python -m pip install ruff nbconvert scanpy scvi-tools
          micromamba run -n human_intestinal ruff check . --output-format=github
          
          # Convert and Compile
          mkdir -p notebooks
          if ls notebooks/*.ipynb 1> /dev/null 2>&1; then
            micromamba run -n human_intestinal jupyter nbconvert --to python notebooks/*.ipynb
            for file in notebooks/*.py; do
              echo "Checking $file..."
              micromamba run -n human_intestinal python -m py_compile "$file"
            done
          fi
